### ISSUE TITLE
Updates required for pimatc 0.9

### ISSUE THREAD

**Issue by mwittig** [Timvdv/pimatic-rfxcom#1]
A couple of changes to your package are required to make it run with the upcoming pimatic release version 0.9. **I'll file a pull request with the necessary changes shortly**. 

As part of the required changes I had to update rfxcom@0.8 as the earlier release of the package did not build with node v4 (which will be used with pimatic 0.9). I also tried to build rfxcom@0.8 with node 0.10.x which worked fine. However, please test the proposed changes as I don't have the hardware to test with in place. If you want to test with my fork directly you can install it as follows: `npm install mwittig/pimatic-rfxcom`. Please also note I have added `device-config-schema.coffee` to the "files" list of the package descriptor as users won't be able to run the plugin, otherwise.

**Comment by Timvdv** [comment]
Thanks for your help! I'm at my parents house at the moment. I'll test this / merge this on Monday!

**Comment by mwittig** [comment]
You're welcome! If you find some time to look into this next week this will be great. Pimatic 0.9 is stabilizing, but there is still some work to do. In particular, we want to make sure we get as much plugins ready for 0.9 to allow for a smooth transition to the new version and to get rid of the legacy as soon as possible :)

**Comment by Timvdv** [comment]
Tested the new changes and everything worked! :+1:

**Comment by mwittig** [comment]
Sounds great! Did you already publish a new version?

**Comment by Timvdv** [comment]
yes I did, the most recent version is published to NPM

**Comment by mwittig** [comment]
Ah, ok. I was just wondering as the README shown on npmjs looks outdated and the entry is saying version 0.8.1 has been published 2 months ago. https://www.npmjs.com/package/pimatic-rfxcom

**Comment by mwittig** [comment]
What is the number of the most recent version, please?

**Comment by Timvdv** [comment]
The latest version is: 0.8.2. Probably a weird versioning bug. Pulled the latest version and re-published it to NPM. It now says it's the latest version :)

**Comment by mwittig** [comment]
Thanks for looking into this :+1:
