### ISSUE TITLE
Can this be used with 433MHz transmitter on GPIO?

### ISSUE THREAD

**Issue by srijken** [Timvdv/pimatic-rfxcom#6]
I'm looking for alternatives to openhab, this is one of them. Is only the USB interface supported, or also connection to GPIO pins?

**Comment by Timvdv** [comment]
Phew.. I have no idea! You need to set a 'interface' in the config. There are no such options for declaring pins, so it probably won't work. I really like Pimatic, so no hard feelings but you can also take a look at: https://home-assistant.io. They also support the RFXCom, maybe they support GPIO.

**Comment by Timvdv** [comment]
@srijken I think misunderstood the question, you don't have a RFXCoM but a 433 transmitter. I think Pimatic Homeduino is exactly what you're looking for: https://github.com/pimatic/homeduino
